Repository RooftopGreenLight/urbanIsland-back-end, pull requests merged in 2022-08, with the labels that each got.

#28 Feature/#26
  src/main/java/rooftopgreenlight/urbanisland/api/controller/MemberController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ProfileController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/PasswordRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/PhoneNumberRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/Profile.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/repository/ProfileRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/ProfileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
Labels: Development

#29 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/MemberController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ProfileController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/PasswordRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/PhoneNumberRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/BaseEntity.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundMemberException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundProfileException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/Profile.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/repository/ProfileRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/ProfileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
Labels: enhancement, Development

#30 Feature/#25
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSocketConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/NotFoundChatRoomException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/socket/handler/StompHandler.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRoomResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/Message.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/ChatRoomRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
Labels: Development

#31 Develop
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSocketConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/NotFoundChatRoomException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/socket/handler/StompHandler.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRoomResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/Message.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/ChatRoomRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
Labels: Development

#33 Feature/#32
  .gitignore
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/ProfileDirProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ProfileController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/config/AwsS3Config.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/config/JasyptConfig.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/AwsS3Properties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/FileDirProperties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/JwtProperties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/MailProperties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/File.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/Profile.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/RooftopImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/RooftopImageType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopAddress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetail.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopOption.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopPeopleCount.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/resources/secret.yml
Labels: enhancement, Development

#34 Develop
  .gitignore
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/ProfileDirProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ProfileController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/config/AwsS3Config.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/config/JasyptConfig.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/AwsS3Properties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/FileDirProperties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/JwtProperties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/properties/MailProperties.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/File.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/Profile.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/RooftopImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/RooftopImageType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopAddress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetail.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopOption.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopPeopleCount.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/resources/secret.yml
Labels: enhancement, Development

#36 Feat: 테이블 구조 변경
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/File.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopAddress.java
Labels: enhancement

#37 Fix: #35 - memberId @PK로 수정
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
Labels: bug

#38 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
Labels: Development

#39 Fix: joinChatRoom URL 수정
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
Labels: bug

#40 Fix: stomp endpoint 수정
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSocketConfig.java
Labels: Development

#41 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSocketConfig.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
Labels: bug

#42 Fix: interceptor 재활성화
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSocketConfig.java
Labels: bug

#43 Fix: Endpoint 경로 수정
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSocketConfig.java
Labels: bug

#44 Feat: log 추가
  src/main/java/rooftopgreenlight/urbanisland/api/common/socket/handler/StompHandler.java
Labels: Development

#45 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/common/socket/handler/StompHandler.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRoomResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
Labels: Development

#47 Feature/#46
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/GoogleProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/JwtProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/KakaoProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/MailProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/NaverProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OAuth2Controller.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/JoinRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/Oauth2Service.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/GoogleToken.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/GoogleUserInfo.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/KakaoToken.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/KakaoUserInfo.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/NaverToken.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/NaverUserInfo.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/ExistMemberException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
Labels: Development

#48 OAuth2.0 기능 구현 완료
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/GoogleProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/JwtProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/KakaoProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/MailProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/NaverProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OAuth2Controller.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/JoinRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/Oauth2Service.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/GoogleToken.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/GoogleUserInfo.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/KakaoToken.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/KakaoUserInfo.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/NaverToken.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/dto/NaverUserInfo.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/ExistMemberException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/resources/secret.yml
Labels: Development

#49 Build: Naver redirect_url 수정
  src/main/resources/secret.yml
Labels: enhancement

#50 Feat: Nickname 기능 추가
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/MemberController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/NicknameRequest.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
Labels: Development

#53 Feature/#51
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/APIResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeeImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeeInfoResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeeRequest.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/Address.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundGreenBeeInfoException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/GreenBeeImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/RooftopImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/RooftopImageType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/constant/ImageName.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/constant/ImageType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopAddress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
Labels: Development

#57 Feature/#55
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AdminController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeeInfoResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeePageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerInfoResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/constant/Progress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/GreenBeeImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/OwnerImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/constant/ImageName.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/dto/GreenBeeDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Authority.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/entity/Owner.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/dto/OwnerDto.java
Labels: Development

#58 Develop
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AdminController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeeInfoResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreenBeePageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerInfoResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/constant/Progress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/GreenBeeImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/OwnerImage.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/constant/ImageName.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/dto/GreenBeeDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Authority.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/entity/Owner.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/dto/OwnerDto.java
Labels: Development

#60 Feature/#59
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AdminController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundGreenBeeException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundGreenBeeInfoException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundOwnerException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
Labels: Development

#61 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AdminController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundGreenBeeException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundGreenBeeInfoException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundOwnerException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
Labels: Development

#62 Feature/#56
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/AuthorizationException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetail.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetailType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopOption.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopProgress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
Labels: Development

#63 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/AuthorizationException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetail.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetailType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopOption.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopProgress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
Labels: Development

#66 Feature/#64
  build.gradle
  docker-compose.yml
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/CacheConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/resources/application.yml
Labels: Development

#67 Develop
  build.gradle
  docker-compose.yml
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/CacheConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: Development

#68 Feature/#65
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/constant/Progress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundChatRoomException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundRooftopException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/entity/Owner.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopProgress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/NGRooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopImageDto.java
Labels: Development

#69 Rooftop 조회 수정
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/constant/Progress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundChatRoomException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundRooftopException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/entity/Owner.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/repository/OwnerRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopProgress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/NGRooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopImageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
Labels: Development

#71 Feature/#70
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/constant/Progress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetailType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopGreeningApply.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopGreeningApplyService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/NGRooftopDto.java
Labels: Development

#72 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/constant/Progress.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/entity/GreenBee.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopDetailType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopGreeningApply.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopGreeningApplyService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/NGRooftopDto.java
Labels: Development

#74 Feature/admin rooftop
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AdminController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/NGRooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopImageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
Labels: Development

#75 기능 구현
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AdminController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/NGRooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopImageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
Labels: Development

#77 Rooftop 조건에 따른 동적 조회 구현
  .gitignore
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopSearchCond.java
Labels: Development

#78 Rooftop 조건에 따른 동적 조회 구현
  .gitignore
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopSearchCond.java
Labels: Development

#79 Main 이미지 추가 저장
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/constant/ImageType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
Labels: Development

#80 Feature/grade
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReviewRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopReviewPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopReviewResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/ExistObjectException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NoMatchMemberIdException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundRooftopReviewException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopReview.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
Labels: Development

#81 Develop
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReviewRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopReviewPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopReviewResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/ExistObjectException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NoMatchMemberIdException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/NotFoundRooftopReviewException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopReview.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
Labels: Development

#83 Feature/get rooftop
  client/greenbee.http
  client/owner.http
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreeningApplyPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreeningApplyResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopReviewResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/ExistMemberException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopPeopleCount.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopReview.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopGreeningApplyService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopReviewDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopSearchCond.java
Labels: Development

#84 Develop
  client/greenbee.http
  client/owner.http
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreeningApplyPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreeningApplyResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopPageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopReviewResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/common/exception/ExistMemberException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopPeopleCount.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopReview.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopGreeningApplyService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopReviewDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopSearchCond.java
Labels: enhancement, Development

#85 Develop
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopSearchCond.java
Labels: enhancement

#86 Fix: GreenBee 중복 신청 수정
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
Labels: bug

#87 Develop
  client/owner.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/owner/service/OwnerService.java
Labels: bug

#88 Feature/rooftop progress
  client/owner.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreeningApplyResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopGreeningApplyService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
Labels: Development

#89 Develop
  client/owner.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/OwnerController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/GreeningApplyResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopGreeningApplyRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopGreeningApplyService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/GreeningApplyPageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
Labels: Development

#90 Fix: 녹화 안 된 옥상 응답 형식 수정
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
Labels: Development

#91 Feature/redis
  client/greenbee.http
  client/rooftop.http
  client/user.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/CacheConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/RedisConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/AccessException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/api/util/constant/RedisKey.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopImageDto.java
Labels: Development

#92 Develop
  client/greenbee.http
  client/rooftop.http
  client/user.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/CacheConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/RedisConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/AccessException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/api/util/constant/RedisKey.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopImageDto.java
Labels: Development

#93 Feat: 로그인 수정
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/Oauth2Service.java
Labels: Development

#94 Develop
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
Labels: Development

#96 Fix: 조회 오류 수정
  client/greenbee.http
  client/user.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/GreenBeeController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/repository/GreenBeeRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopPageDto.java
Labels: Development

#101 Feature/chatting
  client/rooftop.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRoomResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MessageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopEditRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopOptionResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/ChatRoomRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/dto/ChatRoomDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/dto/MessageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopPeopleCount.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopOptionDto.java
Labels: Development

#102 Feature/reservation
  client/reservation.http
  client/user.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationRequest.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/PaymentStatus.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/PaymentType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/Reservation.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/ReservationOption.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
Labels: Development

#103 Develop
  client/reservation.http
  client/rooftop.http
  client/user.http
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ChatRoomResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MessageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopEditRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopOptionResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/ChatRoomRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/MessageRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/dto/ChatRoomDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/dto/MessageDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/greenbee/service/GreenBeeService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/PaymentStatus.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/PaymentType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/Reservation.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/ReservationOption.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/RooftopPeopleCount.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopOptionDto.java
Labels: Development
