Repository RooftopGreenLight/urbanIsland-back-end, pull requests merged in 2022-09, with the labels that each got.

#104 Develop
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
Labels: bug

#107 Feature/chatting
  client/reservation.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoomType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/ChatRoomRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/dto/ReservationDto.java
Labels: Development

#108 Develop
  client/reservation.http
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/entity/ChatRoomType.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/repository/ChatRoomRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/ChatRoomService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/chat/service/MessageService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/dto/ReservationDto.java
Labels: Development

#109 Feature/batch change status
  build.gradle
  client/reservation.http
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/CustomAuditorAware.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationResponse.java
  src/main/java/rooftopgreenlight/urbanisland/batch/job/ChangeReservationStatusJobConfig.java
  src/main/java/rooftopgreenlight/urbanisland/batch/scheduler/ChangeReservationStatusScheduler.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/Reservation.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/ReservationStatus.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/dto/ReservationDto.java
  src/main/resources/application.yml
Labels: Development

#110 Develop
  build.gradle
  client/reservation.http
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/CustomAuditorAware.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationResponse.java
  src/main/java/rooftopgreenlight/urbanisland/batch/job/ChangeReservationStatusJobConfig.java
  src/main/java/rooftopgreenlight/urbanisland/batch/scheduler/ChangeReservationStatusScheduler.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/Reservation.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/entity/ReservationStatus.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/repository/ReservationRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/dto/ReservationDto.java
  src/main/resources/application.yml
Labels: Development

#111 Fix: 필드명 통일
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopRequest.java
Labels: enhancement

#112 Fix: 오류 수정
  src/main/java/rooftopgreenlight/urbanisland/api/controller/RooftopController.java
Labels: enhancement

#113 Develop
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/RooftopResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/entity/Rooftop.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/ReservationDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
Labels: Development

#114 Develop
  src/main/java/rooftopgreenlight/urbanisland/UrbanIslandApplication.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/CacheConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ChatController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ReservationResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/dto/ReservationDto.java
Labels: Development

#116 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/OwnerImageResponse.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/repository/RooftopRepositoryImpl.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/RooftopService.java
Labels: Development

#117 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ReservationController.java
  src/main/java/rooftopgreenlight/urbanisland/domain/reservation/service/ReservationService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/ReservationDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopDto.java
  src/main/java/rooftopgreenlight/urbanisland/domain/rooftop/service/dto/RooftopReviewDto.java
Labels: Development
