Repository RooftopGreenLight/urbanIsland-back-end, pull requests merged in 2022-07, with the labels that each got.

#8 Swagger 구현 완료
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/SwaggerConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/SwaggerController.java
Labels: enhancement

#10 Swagger 구현 완료
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/SwaggerConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebSecurityConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/SwaggerController.java
Labels: enhancement

#12 Feature/#11 이메일인증
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/DuplicatedMemberException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/MailSendException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/MailProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ResponseDto.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/resources/application.yml
  src/main/resources/secret.yml
Labels: Development

#18 Feature/#16 jwt로직추가
  src/main/java/rooftopgreenlight/urbanisland/api/common/annotation/Jwt.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/annotation/PK.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/ExpiredRefreshTokenException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/NotExpiredAccessTokenException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/NotMatchedRefreshTokenException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/resolver/JwtResolver.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/resolver/PKResolver.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
Labels: Development

#20 Develop
  src/main/java/rooftopgreenlight/urbanisland/api/common/annotation/Jwt.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/annotation/PK.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/ExpiredRefreshTokenException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/NotMatchedRefreshTokenException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/dto/ErrorDetailDto.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/dto/ErrorDto.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtProvider.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/dto/TokenDto.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/resolver/JwtResolver.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/resolver/PKResolver.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/APIErrorResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/APIResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/JoinRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/LoginRequest.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/MemberResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/ResponseDto.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/AuthService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/service/MemberService.java
Labels: enhancement, Development

#23 Feature/#21 s3
  .gitignore
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/AwsS3Config.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/FileIOException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/AwsS3Properties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/ProfileDirProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/resolver/PKResolver.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ProfileController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/APIResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/exception/NotFoundProfileException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/Profile.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/repository/ProfileRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/ProfileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/secret.yml
Labels: Development

#24 Develop
  .gitignore
  build.gradle
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/AwsS3Config.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/config/WebConfig.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/FileIOException.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/advice/ControllerAdvice.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/exception/error/ErrorCode.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/jwt/JwtFilter.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/AwsS3Properties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/properties/ProfileDirProperties.java
  src/main/java/rooftopgreenlight/urbanisland/api/common/resolver/PKResolver.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/AuthController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/ProfileController.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/APIResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/controller/dto/FileResponse.java
  src/main/java/rooftopgreenlight/urbanisland/api/service/FileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/exception/NotFoundProfileException.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/entity/Profile.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/repository/ProfileRepository.java
  src/main/java/rooftopgreenlight/urbanisland/domain/file/service/ProfileService.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/entity/Member.java
  src/main/java/rooftopgreenlight/urbanisland/domain/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/secret.yml
Labels: enhancement, Development
